# This file was generated by GoReleaser. DO NOT EDIT.
cask "dsops" do
  name "dsops"
  desc "Secret management for development and production environments"
  homepage "https://github.com/systmms/dsops"
  version "0.2.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dsops"

  on_macos do
    on_intel do
      url "https://github.com/systmms/dsops/releases/download/v#{version}/dsops_#{version}_darwin_amd64.tar.gz"
      sha256 "386f9a10372807ca761167bcac2b69f4777800fa00439c8bd03832ec69c81e3f"
    end
    on_arm do
      url "https://github.com/systmms/dsops/releases/download/v#{version}/dsops_#{version}_darwin_arm64.tar.gz"
      sha256 "8e39ce2bab4242c79e831b743eaae76a5f2de96745a11ac3a421b9b2aab6159f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/systmms/dsops/releases/download/v#{version}/dsops_#{version}_linux_amd64.tar.gz"
      sha256 "0715898f9fb43377e6b8b95081bb7e1321d7a0851e31f67598d09823893b3e23"
    end
    on_arm do
      url "https://github.com/systmms/dsops/releases/download/v#{version}/dsops_#{version}_linux_arm64.tar.gz"
      sha256 "cbd20b49213a929357b2b5a6eb60bce6d502b9d8f21044df7e1dd20e67cddaff"
    end
  end

  # No zap stanza required
end
