# This file was generated by GoReleaser. DO NOT EDIT.
cask "dsops" do
  name "dsops"
  desc "Secret management for development and production environments"
  homepage "https://github.com/systmms/dsops"
  version "0.2.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dsops"
  bash_completion "completions/dsops.bash"
  zsh_completion "completions/dsops.zsh"
  fish_completion "completions/dsops.fish"

  on_macos do
    on_intel do
      url "https://github.com/systmms/dsops/releases/download/v#{version}/dsops_#{version}_darwin_amd64.tar.gz"
      sha256 "265a25ddf30a4c751f641d67bad2235436a85d06ba31ddfd241cfa6ad06f9af6"
    end
    on_arm do
      url "https://github.com/systmms/dsops/releases/download/v#{version}/dsops_#{version}_darwin_arm64.tar.gz"
      sha256 "5079ef0f9822ab08c55472eeb170a67ed43525a6e171a19e60df3c4b580a41eb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/systmms/dsops/releases/download/v#{version}/dsops_#{version}_linux_amd64.tar.gz"
      sha256 "bd9db82578204299c8cae79e351a405ee3eb2144ac018d563f9461ee002b143b"
    end
    on_arm do
      url "https://github.com/systmms/dsops/releases/download/v#{version}/dsops_#{version}_linux_arm64.tar.gz"
      sha256 "a3d225dbe8d1e6fb8c72abbb8206cb0ab70cfa2ecb02ab43801234df615c950a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dsops"]
    end
  end

  # No zap stanza required
end
